---
title: 2024 screen sector statistics
author: Brian Tarran
date: last-modified
date-format: long
format: revealjs
title-slide-attributes:
  data-background-color: "#e50076"
execute: 
  eval: true
  echo: false
  warning: false
embed-resources: false
---

```{r}
#| label: load-functions
#| file: R/stats.R
```

```{r}
#| label: set file path

file_path <- here::here('data/stats.xlsx')
```

# UK box office and admissions {background-color="#e50076"}

##
```{r}
#| label: uk-box-office
#| fig-width: 8
#| fig-height: 6
#| fig-align: center
#| fig-dpi: 150

sheet_name <- 'uk_box_office'
df <- load_data(file_path, sheet_name)
uk_box_office()
```

##
```{r}
#| label: uk-admissions
#| fig-width: 8
#| fig-height: 6
#| fig-align: center
#| fig-dpi: 150

sheet_name <- 'uk_admissions'
df <- load_data(file_path, sheet_name)
uk_admissions()
```

## 
```{r}
#| label: uk-admissions-month
#| fig-width: 8
#| fig-height: 6
#| fig-align: center
#| fig-dpi: 150

sheet_name <- 'uk_admissions'
df <- load_data(file_path, sheet_name)
uk_admissions_month()
```

# UK and Republic of Ireland box office {background-color="#783df6"}

##
```{r}
#| label: uk-roi-box-office
#| fig-width: 8
#| fig-height: 6
#| fig-align: center
#| fig-dpi: 150

sheet_name <- 'uk_roi_box_office'
df <- load_data(file_path, sheet_name)
uk_roi_box_office()
```

##
```{r}
#| label: uk-market-share
#| fig-width: 8
#| fig-height: 6
#| fig-align: center
#| fig-dpi: 150

sheet_name <- 'uk_film_share'
df <- load_data(file_path, sheet_name)
uk_market_share()
```

##
```{r}
#| label: uk-market-share-indie
#| fig-width: 8
#| fig-height: 6
#| fig-align: center
#| fig-dpi: 150

sheet_name <- 'uk_film_share'
df <- load_data(file_path, sheet_name)
uk_market_share_indie()
```

##
```{r}
#| label: uk-market-share-percent
#| fig-width: 8
#| fig-height: 6
#| fig-align: center
#| fig-dpi: 150

sheet_name <- 'uk_film_share'
df <- load_data(file_path, sheet_name)
uk_market_share_percent()
```

# Film and HETV production spend {background-color="#1197FF"}

```{r}
#| label: set-variables-spend

sheet_name <- 'uk_production_detail'
df <- load_data(file_path, sheet_name)
metric <- 'UK_spend_m'
```

##
```{r}
#| label: all-production-first
#| fig-width: 8
#| fig-height: 6
#| fig-align: center
#| fig-dpi: 150

all_production_first()
```

##
```{r}
#| label: all-production-revised
#| fig-width: 8
#| fig-height: 6
#| fig-align: center
#| fig-dpi: 150

all_production_revised()
```

##
```{r}
#| label: film-hetv-production-revised
#| fig-width: 8
#| fig-height: 6
#| fig-align: center
#| fig-dpi: 150

film_hetv_production_revised()
```

##
```{r}
#| label: film-hetv-production-revised-percentage
#| fig-width: 8
#| fig-height: 6
#| fig-align: center
#| fig-dpi: 150

film_hetv_production_revised_percentage()
```

##
```{r}
#| label: film-production-revised
#| fig-width: 8
#| fig-height: 6
#| fig-align: center
#| fig-dpi: 150

category_select <- 'film'
category_colour <- '#e50076'
title <- 'Film production spend, £ million'
subtitle <- "For <span style='color:#e50076'>**film**</span> 
            starting principal photography in calendar year"
production_revised()
```

##
```{r}
#| label: film-production-breakdown-revised
#| fig-width: 8
#| fig-height: 6
#| fig-align: center
#| fig-dpi: 150

category_select <- 'film'
category_colour <- '#e50076'
title <- 'Film production spend, £ million'
subtitle <- "For <span style='color:#e50076'>**film**</span> 
            starting principal photography in calendar year"
production_breakdown_revised()
```

##
```{r}
#| label: hetv-production-revised
#| fig-width: 8
#| fig-height: 6
#| fig-align: center
#| fig-dpi: 150

category_select <- 'hetv'
category_colour <- '#1197FF'
title <- 'HETV production spend, £ million'
subtitle <- "For <span style='color:#1197FF'>**HETV**</span> 
            starting principal photography in calendar year"
production_revised()
```

##
```{r}
#| label: hetv-production-breakdown-revised
#| fig-width: 8
#| fig-height: 6
#| fig-align: center
#| fig-dpi: 150

category_select <- 'hetv'
category_colour <- '#1197FF'
title <- 'HETV production spend, £ million'
subtitle <- "For <span style='color:#1197FF'>**HETV**</span> 
            starting principal photography in calendar year"
production_breakdown_revised()
```

<!-- # Film and HETV production count {background-color="#1197FF"}

```{r}
#| label: set file path


``` -->